function [anMsr, H1, H2, fbLines, rec] = setPerturbVisualFB(targRMS, bounds, win)
%Overlays for the experiment.
%anMsr = annotation Measurements

%Assume we are using Tongue for the moment
if win == 1                  %ASUS Monitor
    stX = 0;    stY = 0;
    fullW = 1920; fullH = 1080;
else                         %Dell Monitor
    stX = 1920; stY = 0;
    fullW = 1680; fullH = 1050;
end
anMsr.winPos = [stX stY fullW fullH];

%Assuming that perfect RMS lies at 50% of the screen, and the acceptable
%upper and lower bound are set at 45% and 55% of the screen, the edge of
%the screen will correspond to these variables accordingly. This will shift
%with differences in participants varying RMS values
anMsr.targRMS   = targRMS; %Ideally this is between 40-70 dB
anMsr.hRMSrange = bounds*10; %half the possible range of RMS, where each 5% mark represents 'bounds' dB
anMsr.vTopAmp   = anMsr.targRMS + anMsr.hRMSrange; %dB 
anMsr.vBotAmp   = anMsr.targRMS - anMsr.hRMSrange; %dB 

%Starts with some measurements
anMsr.bMar      = 0.05; %Bottom Margin
anMsr.minH      = 0.4;  %From the margin. This will need to change
anMsr.maxH      = 0.5;  %From the margin. This will need to change
anMsr.drawMinH  = anMsr.bMar + anMsr.minH; %45%
anMsr.drawMaxH  = anMsr.bMar + anMsr.maxH; %55% Goal value is 50%

anMsr.lMar      = 0.15; %Left Margin
anMsr.lineWidth = 0.1;  %Arbitrary-Looks good at the moment
anMsr.drawMinW  = anMsr.lMar + anMsr.lineWidth;

anMsr.recWidth  = 0.05; %Arbitrary-Looks good at the moment
anMsr.recHeight = 0.05; %Start at this default
anMsr.recXSt    = anMsr.lMar + (anMsr.lineWidth/2 - anMsr.recWidth/2);
anMsr.recYSt    = anMsr.bMar; %Start at the margin

anMsr.minLx = [anMsr.lMar anMsr.drawMinW];     %First X and Last X
anMsr.minLy = [anMsr.drawMinH anMsr.drawMinH]; %First Y and Last Y
anMsr.maxLx = [anMsr.lMar anMsr.drawMinW];     %First X and Last X
anMsr.maxLy = [anMsr.drawMaxH anMsr.drawMaxH]; %First Y and Last Y

anMsr.recPos = [anMsr.recXSt anMsr.recYSt anMsr.recWidth anMsr.recHeight];

%%%%%%
figure1 = figure('NumberTitle','off','Color',[0 0 0],'Position', anMsr.winPos,'MenuBar','none');

H1 = annotation(figure1,'textbox',[0.46 0.46 0.2 0.2],...
                        'Color',[1 1 1],...
                        'String',{'+'},...
                        'LineStyle','none',...
                        'FontWeight','bold',...
                        'FontSize',160,...
                        'FontName','Arial',...
                        'BackgroundColor',[0 0 0],...
                        'Visible','on');

H2 = annotation(figure1,'textbox',[0.38 0.46 0.2 0.2],...
                        'Color',[1 1 1],...
                        'String',{'eee'},...
                        'LineStyle','none',...
                        'FontWeight','bold',...
                        'FontSize',160,...
                        'FontName','Arial',...
                        'BackgroundColor',[0 0 0],...
                        'visible','off');
                    
rec = annotation(figure1,'rectangle',anMsr.recPos,...
                         'Color',[0 1 0],...
                         'LineStyle','none',...
                         'FaceColor',[0 1 0],...
                         'visible','off');
                     
minLine = annotation(figure1,'line', anMsr.minLx, anMsr.minLy,...
                             'Color',[1 1 1],...
                             'LineStyle', '--',...
                             'LineWidth', 1, ...
                             'visible','off');
                         
maxLine = annotation(figure1,'line', anMsr.maxLx, anMsr.maxLy,...
                             'Color',[1 1 1],...
                             'LineStyle', '--',...
                             'LineWidth', 1, ...
                             'visible','off');
% ticks = 0:0.05:1;
% for i = ticks
%     tickLine = annotation(figure1,'line', [0.05 0.07], [i i],...
%                              'Color',[1 1 1],...
%                              'LineWidth', 1, ...
%                              'visible','on');
%     tickName = annotation(figure1, 'textbox', [0.07 i 0.02 0.02],...
%                                     'string', num2str(i),...
%                                     'color', 'white',...
%                                     'visible','on');
% end
                
fbLines = [minLine maxLine];                     
end